### ISSUE TITLE
Chapter 6 - app.css and app.js not found, result in 404

### ISSUE THREAD

**Issue by bmontgom** [dickeyxxx/mean-sample#16]
Everything is building, gulp is outputting the app.css and app.js files into the /assets directory. This directory by the way is an immediate child of the main application directory. It would look like localhost:3000/assets

Anyways, they are not able to be referenced by posts.html. If I move the app.css and app.js files into the /ng directory, everything works! Clearly this is not supposed to be happening though, and I cannot find any differences between your code and mine. I've gone over your code here in the repo and double checked that I was typing everything in correctly whilst reading the chapter.

Below is my project structure.

![project structure](https://cloud.githubusercontent.com/assets/3969034/6536323/455883c2-c412-11e4-920e-fd7d0dfc4693.png)

This is what happens in chrome:

![image](https://cloud.githubusercontent.com/assets/3969034/6536360/8904f01a-c412-11e4-81d2-557dbe375352.png)

Any help would be appreciated

**Comment by dickeyxxx** [comment]
what does your `server.js` look like?

**Comment by bmontgom** [comment]
Well there are two, so I'll post both of them.

The one in the scripts folder:
~~~~~~~~~~
var gulp = require( "gulp" );
var nodemon = require( "gulp-nodemon" );

gulp.task( "dev:server", function ()
{
    nodemon(
        {
            script: "server.js",
            ext: "js",
            ignore: [ "ng*", "gulp*", "assets*" ]
        }
    );
} );
~~~~~~~~~

The actual node server file:
~~~~~~~~
var express = require( "express" );
var bodyParser = require( 'body-parser' );
var app = express();

app.use( bodyParser.json() );
app.use( "/api/posts", require( "./controllers/api/posts.js" ) );
app.use( require( "./controllers/static.js" ) );

app.listen( 3000, function ()
{
    console.log( 'Server listening on', 3000 );
} );
~~~~~~~~~

**Comment by dickeyxxx** [comment]
ah what's in `~/controllers/static.js`?

**Comment by bmontgom** [comment]
var express = require("express");
var router = express.Router();

router.get( "/", function ( req, res )
{
    var path = require("path");
    res.sendFile( path.resolve() + "/views/posts.html" );
} );

router.use(express.static(__dirname + "/../ng"));

module.exports = router;

**Comment by dickeyxxx** [comment]
you only have the ng folder added, you need to add the assets one as well

**Comment by bmontgom** [comment]
Ok would that be done by adding

router.use( express.static( __dirname + "/../assets" ) );  ?

**Comment by dickeyxxx** [comment]
right

**Comment by bmontgom** [comment]
Ok thanks for the help. Was I just supposed to infer that this line would need to be included? I don't remember seeing anything about it in the chapter. Unfortunately I haven't been able to talk to any of my fellow students about this, so it's just been my own two eyes rereading the chapter; I'm sure I easily could have missed it.

**Comment by dickeyxxx** [comment]
I'm fairly certain it's mentioned. Chiefly because I haven't heard of any issues with this yet, but if someone else chimes in on here with a similar problem I'll make sure.

**Comment by BillLucky** [comment]
Look this : [Not loading and 404 for javascript files #104](https://github.com/airbnb/airpal/issues/104)
