### ISSUE TITLE
Post request fails in Chapter 4

### ISSUE THREAD

**Issue by vishivish18** [dickeyxxx/mean-sample#21]
After changing server.js to listen to listento q post request on http://localhost:3000/api/posts and defining the model it is still giving an error in postman
I am sending key value pair in post man as below image
(if i am removing the required condition from username and body then its saving an empty data in the collection)

![postmanerror](https://cloud.githubusercontent.com/assets/3650542/7217274/07e5ad56-e63d-11e4-84f6-8d7f26d4549f.PNG)

**Comment by Alayode** [comment]
You should check to make sure you are not using Post on any other app on your local device computer or sandbox for that matter. I would reset my  terminal/commandline  and try again.

**Comment by 3barney** [comment]
add the following piece
<code>app.use(bodyParser.urlencoded({extended: true}));</code>
 before
<code>app.use(bodyParser.json());</code>

it resolved my issue using postman

**Comment by warhost** [comment]
Try these settings:

![image](https://cloud.githubusercontent.com/assets/15911990/21934067/5243d070-d9a8-11e6-8515-f438c343e9f1.png)

![image](https://cloud.githubusercontent.com/assets/15911990/21934088/647b0088-d9a8-11e6-898b-8012bfb5dcee.png)

**Comment by vishivish18** [comment]
@warhost I even forgot about this thing , I had this issue long time back, but thanks for your reply though, I appreciate it 👍 
I am closing this now
