### ISSUE TITLE
The curl command does not work for me in chapter 4

### ISSUE THREAD

**Issue by Alayode** [dickeyxxx/mean-sample#25]
Using mongoose models with the post endpoint

admins-mbp:~ admin$ curl -v -H "Content-Type:application/json" -XPOST --data "{\"username\":\"dickeyxxx\",\"body\":\"node rules\"}" http://localhost:3000/api/posts/
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused
admins-mbp:~ admin$
admins-mbp:~ admin$
admins-mbp:~ admin$
admins-mbp:~ admin$ curl -v -H "Content-Type:application/json" -XPOST --data "{\"username\":\"dickeyxxx\",\"body\":\"node rules\"}" http://localhost:3000/api/posts
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused
admins-mbp:~ admin$ sudo curl -v -H "Content-Type:application/json" -XPOST --data "{\"username\":\"dickeyxxx\",\"body\":\"node rules\"}" http://localhost:3000/api/posts
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 3000 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 3000 failed: Connection refused
* Failed to connect to localhost port 3000: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 3000: Connection refused

Here in the code I am trying test to see if the post work but it is saying the connection is refused the server is up and the folder is  not in the root so when i install node modules i must use sudo npm install in order for it to work. 

I am not sure if this is a big issue but I am able to see my 201 come back after each refresh so no issues there. I would like to know how to use curl to test this though.

thanks

**Comment by dickeyxxx** [comment]
is your server running on port 3000?

**Comment by Alayode** [comment]
yes the server is running on port 3000 and i then open a new window in my terminal and then run that curl command.

**Comment by Alayode** [comment]
I was able to resolve this issue apparently I added nodemon and all the components for chapter 5 up until FIXING THE POST ORDERING I will leave a link to a screenshot doing so I have multiple local servers running at the moment and maybe there was some sort of conflict. 
https://www.dropbox.com/s/yds4hpkkoo22xol/Screenshot%202015-04-29%2017.09.21.png?dl=0

**Comment by alexhong38** [comment]
Im having the same issue and not really understanding the fix for this. I tried to uninstall nodemon and still "Connection refused". What was it that you exactly did to fix the connection issue? Thanks in advance.
