### ISSUE TITLE
CH08, question about using '_' ?

### ISSUE THREAD

**Issue by fkkcloud** [dickeyxxx/mean-sample#29]
Hi,

I am in the stage of putting user name once user login successfully in nav-tab right side in chapter 8.

I see this implementation example.
angular.module('app')
.controller('ApplicationCtrl', function($scope){
	$scope.$on('login', function(_, user){
		$scope.currentUser = user
	})
})

What is _ being used for for this case?

**Comment by dickeyxxx** [comment]
nothing. `_` is just a convention for an argument you won't use
